---
engines:
  duplication:
    enabled: true
    config:
      languages:
        - ruby
  fixme:
    enabled: true
  rubocop:
    enabled: true
ratings:
  paths:
    - bin/
    - lib/
exclude_paths:
  - spec/
